Code-Hammers/code-hammers

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/app/hooks.ts
client/src/app/store.ts
client/src/components/Login.tsx
client/src/features/user/userSlice.ts
client/src/index.tsx
client/src/pages/MainPage.tsx
package.json

Redux setup

---

client/src/App.tsx
client/src/AuthenticatedApp.tsx
client/src/components/Banner/Banner.test.tsx
client/src/pages/MainPage/MainPage.tsx
client/src/pages/NotFoundPage/NotFoundPage.test.tsx
client/src/pages/NotFoundPage/NotFoundPage.tsx
client/src/pages/NotFoundPage/__snapshots__/NotFoundPage.test.tsx.snap

- Added basic NotFoundPage for 404 displays
- Implemented client side 404 handling
- Added basic test file for NotFoundPage
- Refactored a couple of component types

Added client side 404 handling including NotFound Page and testing

---

server/controllers/userController.ts
server/routes/userRoutes.ts

-refactored user routes to return server responses directly from controllers.

Route refactor

---

client/src/App.test.tsx
client/src/AuthenticatedApp.test.tsx

file structure changes

---

__tests__/userController.tests.ts
__tests__/userRoutes.test.ts
client/src/AuthenticatedApp.tsx
client/src/components/ProfileThumb/ProfileThumb.tsx
client/src/pages/Profiles/Profiles.tsx
client/src/pages/Profiles/__snapshots__/Profiles.test.tsx.snap
client/types/profile.ts
server/controllers/profileController.ts
server/controllers/userController.ts
server/models/profileModel.ts
server/models/userModel.ts
server/types/profile.ts
server/types/user.ts

- Created a display component to render individual profile thumbs on the profiles page. 
- Added firstName and lastName fields to the user and profile models.
- Updated all associated routes.
- Updated all type files.
- Updated all existing tests. 
N/A
1. Run test suites with `npm run test:all` and ensure all tests pass.
2. Spin up the app locally using `npm run docker-dev`.
3. Use log in credentials email: tester@codehammers.com password: ilovetesting.
4. Navigate to the profiles tab and ensure profile thumbs are rendered correctly.
N/A

ProfileThumb Display Component Created for Rendering Profile Thumbs on Profiles Page

---

TODOS_GENERAL
client/src/features/user/userSlice.test.ts
client/src/features/user/userSlice.ts
client/src/pages/MainPage/MainPage.tsx
client/src/pages/Profile/Profile.tsx
client/types/user.ts

Added test file for userSlice to increase unit testing on existing codebase. Also made some adjustments to the thunk logic for login.
N/A
1. Run test suites with npm run test:all and ensure all tests pass.
2. Spin up the app locally using npm run docker-dev.
3. Use log in credentials email: [tester@codehammers.com](mailto:tester@codehammers.com) password: ilovetesting and ensure login functionality is maintained for correct credentials.
4. Use various combinations of incorrect or incomplete credentials and ensure functionality is maintained.
N/A

Add Tests for userSlice

---

docs/TypeScript.md

Part of the ongoing effort to improve documentation and help files.
N/A
N/A

Add TypeScript Guidance To Documentation Files

---

.gitignore
client/src/AuthenticatedApp.tsx
client/src/components/Navbar/Navbar.tsx
client/src/components/Navbar/__snapshots__/Navbar.test.tsx.snap
client/src/pages/DirectoryPage/DirectoryPage.tsx
client/src/pages/DirectoryPage/__snapshots__/DirectoryPage.test.tsx.snap

This ticket is part of [CHE-15](https://codehammers.atlassian.net/browse/CHE-18?atlOrigin=eyJpIjoiMmE3NGU2MWNlYmQ5NDc1NDgxZTE3NDRmMmQ5NmE4OTEiLCJwIjoiaiJ9) Create Alumni Directory story and sets up the routing and Navigation for the DirectoryPage component.
[CHE-18](https://codehammers.atlassian.net/browse/CHE-18?atlOrigin=eyJpIjoiMmE3NGU2MWNlYmQ5NDc1NDgxZTE3NDRmMmQ5NmE4OTEiLCJwIjoiaiJ9)
1. `git fetch`
2. `git checkout CHE-18/subtask/Create-Navigation-and-Routes-to-Directory-Page`
3. `npm run docker-dev` --> verify core functionality is present
N/A

[CHE-18] Create Navigation and Routes to Directory Page

---

client/webpack.config.js

Reload quickfix

---

dev-tools/scripts/alumniDatabaseSeeder.ts
server/controllers/devControllers.ts
server/index.ts
server/models/graduateInvitationModel.ts
server/routes/devRoutes.ts
server/types/graduateInvitation.ts

This ticket is part of [CHE-23](https://codehammers.atlassian.net/browse/CHE-23?atlOrigin=eyJpIjoiMWMwMzUwMDMwZTBkNGFkYWI5NTZhMWJmYjM5ZGYwYTkiLCJwIjoiaiJ9) Create User Registration story and adds the graduateInvitation model as well as its type file. It also contains the work for [CHE-43](https://codehammers.atlassian.net/browse/CHE-43?atlOrigin=eyJpIjoiNTBjNDA1YTQ0OThiNDU1M2I2YmE0YWFhOThmMzczZGIiLCJwIjoiaiJ9) adding a seeding script and dev routes for testing.
[CHE-40](https://codehammers.atlassian.net/browse/CHE-40?atlOrigin=eyJpIjoiYTU2ZDg2NTUyOWQ3NDY0NWJmMzc0OWRiNWZhZWJiMWQiLCJwIjoiaiJ9)
N/A
N/A
[CHE-23]: https://codehammers.atlassian.net/browse/CHE-23?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHE-40]: …

[CHE-40] Create User Registration

---

client/src/pages/RegistrationPage/RegistrationPage.tsx

This ticket is part of [CHE-23](https://codehammers.atlassian.net/browse/CHE-18?atlOrigin=eyJpIjoiMmE3NGU2MWNlYmQ5NDc1NDgxZTE3NDRmMmQ5NmE4OTEiLCJwIjoiaiJ9) Create User Registration story and adds state update and redirect functionality when registration is successful.
[CHE-45](https://codehammers.atlassian.net/browse/CHE-45?atlOrigin=eyJpIjoiYjE2ZTYxNWEzYzgwNGU3Y2FkYjUzYjBjYTIzZjAzN2UiLCJwIjoiaiJ9)
[CHE-44](https://codehammers.atlassian.net/browse/CHE-45?atlOrigin=eyJpIjoiYjE2ZTYxNWEzYzgwNGU3Y2FkYjUzYjBjYTIzZjAzN2UiLCJwIjoiaiJ9)
1. Spin up Dev server using `npm run docker-dev`
2. In the browser navigate to `http://localhost:8080/registration` using a valid token (eg: http://localhost:8080/registration? 
token=0d715e45b98bebbcbf5739c727a4c1c38dc80950) and register a new user. Confirm state …

[CHE-45] Hook Up To Redux State

---

client/src/pages/EditProfilePage/EditProfilePage.tsx

[### Description
This ticket is part of [CHE-2](https://codehammers.atlassian.net/browse/CHE-2?atlOrigin=eyJpIjoiNTY3YjliODk5NjY2NGJiNzg1NTdiZjk0MDYzYTc1ZjIiLCJwIjoiaiJ9) Create Profile Page story and adds some very basic placeholder styling.
[CHE-47](https://codehammers.atlassian.net/browse/CHE-47?atlOrigin=eyJpIjoiNDljYTk2YTg0YWMxNDg1NThhOTA0NWJlYTg2NzcyNDgiLCJwIjoiaiJ9)
1. Ensure branches are up to date.
2. `git checkout CHE-7/subtask/Create-EditProfile-Page`
3. `npm run docker-dev` --> Test edit functionality and ensure styling didn't break anything.
N/A
[CHE-2]: https://codehammers.atlassian.net/browse/CHE-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHE-47]: https://codehammers.atlassian.net/browse/CHE-47?atlOrigin=eyJpIjoiNWRkNTljNz …

CHE-47 Add Basic Styling To EditProfile Page

---

server/models/forumModel.ts
server/models/postModel.ts
server/models/threadModel.ts

This ticket is part of [CHE-3](https://codehammers.atlassian.net/browse/CHE-3?atlOrigin=eyJpIjoiYzBmMjNlNjY5MDU2NGNhMmJhNDQ1ZGVhNTcxNTJmYzciLCJwIjoiaiJ9) story Create Forums Page and adds models for forums, threads and posts.
[CHE-57](https://codehammers.atlassian.net/browse/CHE-3?atlOrigin=eyJpIjoiZjJkNjRiMWUxMjUzNDBmZTg3ODQyZmJhY2Q2YTM2NTciLCJwIjoiaiJ9)
N/A
N/A
[CHE-3]: https://codehammers.atlassian.net/browse/CHE-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHE-57]: https://codehammers.atlassian.net/browse/CHE-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHE-57] Create Database Models

---

client/src/AuthenticatedApp.tsx
client/src/components/Header/Header.tsx

Refactored and improved Navbar and Banner functionality.
NOTE: Dev branch requires image update for dependencies.
N/A
N/A
N/A

Navigation and Banner Refactor

---

client/src/pages/Profile/Profile.test.tsx
client/src/pages/Profile/Profile.tsx

This ticket is part of [CHE-2](https://codehammers.atlassian.net/browse/CHE-2?atlOrigin=eyJpIjoiMjg4ZmY3M2FlNDA1NDQyMzhlNDllNjcyMjgwZWE4Y2QiLCJwIjoiaiJ9) story Create Profile Page and adds some basic styling to the Profile component. 
[CHE-60](https://codehammers.atlassian.net/browse/CHE-60?atlOrigin=eyJpIjoiZGRiNzc4ZjgzZmFiNDEzOTliNmIyZTMwNjI1YzQ5MWMiLCJwIjoiaiJ9)
N/A
N/A
[CHE-2]: https://codehammers.atlassian.net/browse/CHE-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHE-60]: https://codehammers.atlassian.net/browse/CHE-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHE-60] Improve Profile Page Styling

---

client/src/components/Header/Header.tsx
client/src/pages/EditProfilePage/EditProfilePage.tsx
client/src/pages/Profile/Profile.tsx
client/src/pages/Profiles/Profiles.tsx

This ticket is part of [CHE-2](https://codehammers.atlassian.net/browse/CHE-2?atlOrigin=eyJpIjoiMjg4ZmY3M2FlNDA1NDQyMzhlNDllNjcyMjgwZWE4Y2QiLCJwIjoiaiJ9) story Create Profile Page and hooks up the EditProfilePage as well as adds some basic styling to the component. 
[CHE-61](https://codehammers.atlassian.net/browse/CHE-61?atlOrigin=eyJpIjoiOTA0YzhiNzQyYzIxNGJhZWExMzYzY2I3ZmFjNmNhNGIiLCJwIjoiaiJ9)
N/A
Please go through each item of this checklist carefully.
N/A
[CHE-2]: https://codehammers.atlassian.net/browse/CHE-2?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHE-61]: https://codehammers.atlassian.net/browse/CHE-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHE-61] Update Styling For EditProfilePage And Expand Functionality

---

client/src/components/Login/Login.tsx
client/src/pages/LandingPage.tsx

Landing Page and Login Styling

Landing Page and Login Styling

---

client/src/pages/DirectoryPage/DirectoryPage.tsx
server/controllers/alumniControllers.ts

Quick styling and Pagination update.

Updated some styling and added pagination functionality

---

client/src/components/modals/AlumniModal/AlumniModal.tsx
client/src/pages/DirectoryPage/DirectoryPage.tsx
client/types/alum.ts

Modal and styling added

---

README.md

Thank you for your contribution to Code Hammers's repository! Before merging, please fill out this brief form.
Refactored and added additional content to README
[CHE-38](https://codehammers.atlassian.net/jira/software/projects/CHE/boards/3?selectedIssue=CHE-38)
Proof read it
Please go through each item of this checklist carefully.
(This is space for any additional information or attachments you'd like to add as part of this PR.)
[CHE-38]: https://codehammers.atlassian.net/browse/CHE-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHE-38] Updated README

---

README.md

CHE-38 Added more things

---

server/index.ts

Quick health check endpoint added for load balancer set up.

health check endoint added for load balancer set up

---

client/src/pages/RegistrationPage/RegistrationPage.tsx

This PR adds basic styling to the Registration Page making it consistent with the overall theme. As part of this work, a second password input was added to perform a check to make sure the user entered the password they want to register with correctly.
[CHE-70](https://codehammers.atlassian.net/browse/CHE-70?atlOrigin=eyJpIjoiYjI0ZDU1NTNhNGVhNDU1MjlkM2JiOWMzNDYyOThiNWQiLCJwIjoiaiJ9)
N/A
N/A
[CHE-70]: https://codehammers.atlassian.net/browse/CHE-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHE-70] Registration Page Styling

---

client/src/components/Login/Login.tsx
client/src/pages/RegistrationPage/RegistrationPage.tsx

This PR adjusts the input field text color for the login component and registration page forms.
N/A
N/A
N/A

Changed text color for input fields

---

client/src/components/Header/Header.tsx

This PR fixes a Nav issue where once the user leaves the main page they cannot return. I made the Codehammers logo and text clickable and it returns the user to main.
N/A
N/A
N/A

Quick Nav fix

---

client/src/components/Forums/CreatePost/CreatePost.tsx

This PR fixes the color of the text in the input field for posts.
N/A
N/A
N/A

Input Field FOnt Fix

---

client/src/pages/EditProfilePage/EditProfilePage.tsx

This PR removes the firstName and lastName fields from the EditProfile form.
[CHE 146](https://codehammers.atlassian.net/browse/CHE-146?atlOrigin=eyJpIjoiMjIwZTFhMzAxZGQ2NGI4ZWEyYzYxN2JiNjY2ZmViODYiLCJwIjoiaiJ9)
N/A
N/A

[Che 146] Update Edit Profile Form

---

dev-tools/scripts/alumniDatabaseSeeder.ts

QUick seeder fix

---

client/src/pages/Profile/Profile.tsx
dev-tools/scripts/alumniDatabaseSeeder.ts
server/controllers/userController.ts
server/models/graduateInvitationModel.ts
server/types/graduateInvitation.ts

This PR updates several files to automatically add the user's cohort to their profile on successful registration.
[CHE 151](https://codehammers.atlassian.net/browse/CHE-151?atlOrigin=eyJpIjoiZTFiYmYwY2I4OWQwNGNmNWI4Mjc3NzQ2M2QwMjUzMmIiLCJwIjoiaiJ9)
N/A
N/A

[Che 151] Update Registration Flow To Add Cohort

---

package.json

Cowboy Script Fix - Yeeeeehaaaaaa!!!!

script fix

---

server/config/testGoogleAPI.ts

Last quick fix for deployment bug

---

client/src/pages/RegistrationPage/RegistrationPage.tsx

This PR removed some unused fields from the registration page.
[CHE-153](https://codehammers.atlassian.net/browse/CHE-153?atlOrigin=eyJpIjoiNGFlYWRlZTdjZTg2NDU0OGEwOGRiNmViOTY0ZDExNjAiLCJwIjoiaiJ9)
N/A
N/A
[CHE-153]: https://codehammers.atlassian.net/browse/CHE-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHE-153] Remove Name Fields

---

server/routes/alumniRoutes.ts
server/routes/forumRoutes.ts
server/routes/imageRoutes.ts
server/routes/profileRoutes.ts
server/routes/userRoutes.ts

This PR adds protection middleware to all sensitive routes.
[CHE-154](https://codehammers.atlassian.net/browse/CHE-154?atlOrigin=eyJpIjoiOTljNTg2OTZiY2I1NDE1MmFhMzlhOWQwNWZhODE3NjEiLCJwIjoiaiJ9)
N/A
N/A
[CHE-154]: https://codehammers.atlassian.net/browse/CHE-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CHE-154] Add Auth Middleware To Remaining Routes

---

docker-compose-test.yml
package.json
scripts/docker-remove-all.sh

- adds a script folder with shell script to find and remove all codehammer containers, images and volumes from local docker system
- add npm script in root package.json to run above script
- add "command" field in docker-compose-test.yml to mute mongo container logs
N/A
- run `npm run docker-dev`, shut it down, run `npm run docker-test:all` until it completes. View containers, images, and volumes on docker desktop. Run `npm run docker-remove-all` and confirm all containers/images/volumes are removed
- run `npm run docker-test:all` and confirm no logs are displayed from mongo container
DevOps ain't for me

[NO-TICKET] Add script to remove codehammers containers, images & volumes from local docker system (and mute mongo container logs)
